---
version: "3.6"

services:

  consumer:
    image: notify-queue-consumer:latest
    build: .
    command: ["php", "-f", "public/consumer.php"]

  test-ci:
    image: notify-queue-consumer:latest
    command:
      - "./vendor/bin/phpunit"
      - "--configuration=phpunit.xml"
      - "--testsuite=unit"
      - "--log-junit=build/output/unit-tests.xml"

  phpstan-ci:
    image: notify-queue-consumer:latest
    command:
      - "./vendor/bin/phpstan"
      - "analyse"
      - "--level=7"
      - "/var/www/src"

  test:
    image: notify-queue-consumer:latest
    volumes:
      - .:/var/www
    command:
      - "./vendor/bin/phpunit"
      - "--configuration=phpunit.xml"
      - "--testsuite=unit"
      - "--log-junit=build/output/unit-tests.xml"

  phpstan:
    image: notify-queue-consumer:latest
    volumes:
      - .:/var/www
    command:
      - "/var/www/vendor/bin/phpstan"
      - "analyse"
      - "--level=7"
      - "/var/www/src"

  lint:
    image: cytopia/phpcs:latest-php7.4
    volumes:
      - ./src:/data/src
      - ./public:/data/public
    command:
      - -p
      - --report=checkstyle
      - --standard=PSR12
      - --warning-severity=0
      - /data/src
      - /data/public

  localstack:
    image: localstack/localstack:0.10.5
    environment:
      DEFAULT_REGION: eu-west-1
      HOSTNAME_EXTERNAL: localstack
      SERVICES: sqs
    volumes:
      - "./scripts/localstack:/docker-entrypoint-initaws.d"
