---
version: "3.6"

services:

  consumer:
    image: notify-queue-consumer:latest
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        ENABLE_DEV_DEPS: "true"
    env_file: [local.env]

  phpqa:
    image: jakzal/phpqa:php7.4-alpine
    build:
      context: .
      dockerfile: docker/phpqa/Dockerfile

  phpstan:
    image: jakzal/phpqa:php7.4-alpine
    volumes:
      - .:/app
    command:
      - "phpstan"
      - "analyse"
      - "-c"
      - "/app/tests/phpstan.neon"

  lint:
    image: jakzal/phpqa:php7.4-alpine
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    command:
      - phpcs
      - -p
      - --report=checkstyle
      - --standard=PSR12
      - --warning-severity=0
      - /app/src
      - /app/public

  phpmd:
    image: jakzal/phpqa:php7.4-alpine
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    command:
      - phpmd
      - /app/src/NotifyQueueConsumer
      - text
      - codesize,unusedcode,naming

  test:
    image: jakzal/phpqa:php7.4-alpine
    volumes:
      - .:/app
    command:
      - "php"
      - "-dpcov.enabled=1"
      - "-dpcov.directory=."
      - "-dpcov.exclude=\"~vendor~\""
      - "/app/vendor/bin/phpunit"
      - "--configuration=/app/tests/phpunit.xml"
      - "--coverage-text"
      - "--log-junit=/app/test-results/unit/results.xml"
      - "--testsuite=unit"

  test-functional:
    image: notify-queue-consumer:latest
    depends_on:
      - localstack
      - mock-notify
    volumes:
      - .:/var/www
    command:
      - "/var/www/vendor/bin/phpunit"
      - "--configuration=/var/www/tests/phpunit.xml"
      - "--no-coverage"
      - "--log-junit=/var/www/test-results/functional/results.xml"
      - "--testsuite=functional"
    env_file: [local.env]
    networks:
      - internal

  test-functional-ci:
    image: notify-queue-consumer:latest
    depends_on:
      - localstack
      - mock-notify-ci
    command:
      - "/var/www/vendor/bin/phpunit"
      - "--configuration=/var/www/tests/phpunit.xml"
      - "--no-coverage"
      - "--log-junit=/var/www/test-results/functional/results.xml"
      - "--testsuite=functional"
    env_file: [local.env]
    networks:
      - internal

  localstack:
    image: localstack/localstack:0.10.5
    environment:
      DEFAULT_REGION: eu-west-1
      HOSTNAME_EXTERNAL: localstack
      SERVICES: sqs,s3
      DEBUG: 1
    volumes:
      - "./scripts/localstack:/docker-entrypoint-initaws.d"
      - "./tests/fixtures:/tmp/fixtures"
    networks:
      - internal

  mock-notify:
    image: stoplight/prism:3
    container_name: mock-notify
    build:
      context: .
      dockerfile: docker/mock-notify/Dockerfile
    command:
      - "mock"
      - "-h"
      - "0.0.0.0"
      - "/app/mock-notify/openapi.yml"
    volumes:
      - "./docker/mock-notify:/app/mock-notify"
    ports:
      - "4010:4010"
    networks:
      - internal

  mock-notify-ci:
    image: stoplight/prism:3
    container_name: mock-notify
    build:
      context: .
      dockerfile: docker/mock-notify/Dockerfile
    command:
      - "mock"
      - "-h"
      - "0.0.0.0"
      - "/app/mock-notify/openapi.yml"
    ports:
      - "4010:4010"
    networks:
      - internal

networks:
  internal:
    driver: bridge
