---
version: "3.6"

services:

  php:
    build: ./
    image: opg-notify-queue-consumer_php

  consumer:
    image: opg-notify-queue-consumer_php:latest
    command: ["php", "-f", "public/consumer.php"]

  test:
    image: opg-notify-queue-consumer_php:latest
    build: ./
    command:
      - "./vendor/bin/phpunit"
      - "--configuration=phpunit.xml"
      - "--testsuite=unit"
      - "--log-junit=/output/consumer-unit.xml"
