---
version: "3.6"

services:

  consumer:
    image: notify-queue-consumer:latest
    build: .
    env_file: [local.env]

  test-ci:
    image: notify-queue-consumer:latest
    volumes:
      - ./test-results/:/var/www/test-results
    command:
      - "./vendor/bin/phpunit"
      - "--configuration=phpunit.xml"
      - "--testsuite=unit"
      - "--log-junit=/var/www/test-results/unit/results.xml"

  phpstan-ci:
    image: notify-queue-consumer:latest
    volumes:
      - ./test-results:/var/www/test-results
    command:
      - "/var/www/vendor/bin/phpstan"
      - "analyse"
      - "--level=7"
      - "/var/www/src"

  pcov:
    image: notify-queue-consumer-pcov:latest
    build:
      context: .
      dockerfile: docker/pcov/Dockerfile
    volumes:
      - ./test-results:/var/www/test-results
    command:
      - "php"
      - "-dpcov.enabled=1"
      - "-dpcov.directory=/var/www/"
      - "-dpcov.exclude=\"~/var/www/vendor~\""
      - "/var/www/vendor/bin/phpunit"
      - "--configuration=/var/www/phpunit.xml"
      - "--coverage-text"
      - "--coverage-clover=/var/www/test-results/pcov/results.xml"
      - "--log-junit=/var/www/test-results/unit/results.xml"
      - "--testsuite=unit"

  test:
    image: notify-queue-consumer:latest
    volumes:
      - .:/var/www
    command:
      - "/var/www/vendor/bin/phpunit"
      - "--configuration=phpunit.xml"
      - "--testsuite=unit"
      - "--log-junit=/var/www/test-results/unit/results.xml"

  phpstan:
    image: notify-queue-consumer:latest
    volumes:
      - .:/var/www
    command:
      - "/var/www/vendor/bin/phpstan"
      - "analyse"
      - "--level=7"
      - "/var/www/src"

  lint:
    image: cytopia/phpcs:latest-php7.4
    volumes:
      - ./src:/data/src
      - ./public:/data/public
    command:
      - -p
      - --report=checkstyle
      - --standard=PSR12
      - --warning-severity=0
      - /data/src
      - /data/public

  localstack:
    image: localstack/localstack:0.10.5
    environment:
      DEFAULT_REGION: eu-west-1
      HOSTNAME_EXTERNAL: localstack
      SERVICES: sqs,s3
      DEBUG: 1
    ports:
      - "4572:4572"
      - "4576:4576"
    volumes:
      - "./scripts/localstack:/docker-entrypoint-initaws.d"
      - "./tests/fixtures:/tmp/fixtures"
