---
version: "3.7"

services:

  consumer:
    image: notify-queue-consumer:latest
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        ENABLE_DEV_DEPS: "true"
    env_file: [local.env]

  phpstan:
    image: jakzal/phpqa:php8.2-alpine
    volumes:
      - .:/app
    command:
      - "phpstan"
      - "analyse"
      - "-c"
      - "/app/tests/phpstan.neon"

  lint:
    image: jakzal/phpqa:php8.2-alpine
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    command:
      - phpcs
      - -p
      - --report=checkstyle
      - --standard=PSR12
      - --warning-severity=0
      - /app/src
      - /app/public

  phpmd:
    image: jakzal/phpqa:php8.2-alpine
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    command:
      - phpmd
      - /app/src/NotifyQueueConsumer
      - text
      - codesize,unusedcode,naming

  test:
    image: jakzal/phpqa:php8.2-alpine
    volumes:
      - .:/app
    command:
      - "php"
      - "-dpcov.enabled=1"
      - "-dpcov.directory=/app"
      - "-dpcov.exclude=\"~vendor~\""
      - "/app/vendor/bin/phpunit"
      - "--configuration=/app/tests/phpunit.xml"
      - "--coverage-text"
      - "--log-junit=/app/test-results/unit/results.xml"
      - "--testsuite=unit"

  test-functional:
    image: notify-queue-consumer:latest
    depends_on:
      localstack:
        condition: service_healthy
      consumer-mock-notify:
        condition: service_healthy
      consumer-mock-sirius:
        condition: service_healthy
    volumes:
      - .:/var/www
    command:
      - "/var/www/vendor/bin/phpunit"
      - "--configuration=/var/www/tests/phpunit.xml"
      - "--no-coverage"
      - "--log-junit=/var/www/test-results/functional/results.xml"
      - "--testsuite=functional"
    env_file: [local.env]

  test-functional-ci:
    image: notify-queue-consumer:latest
    depends_on:
      localstack:
        condition: service_healthy
      mock-notify-ci:
        condition: service_healthy
      mock-sirius-ci:
        condition: service_healthy
    command:
      - "/var/www/vendor/bin/phpunit"
      - "--configuration=/var/www/tests/phpunit.xml"
      - "--no-coverage"
      - "--log-junit=/var/www/test-results/functional/results.xml"
      - "--testsuite=functional"
    env_file: [local.env]

  localstack:
    image: localstack/localstack:2.0.0
    environment:
      DEFAULT_REGION: eu-west-1
      HOSTNAME_EXTERNAL: localstack
      SERVICES: sqs,s3
      DEBUG: 1
    volumes:
      - "./scripts/localstack/init:/etc/localstack/init/ready.d"
      - "./scripts/localstack/wait:/scripts/wait"
      - "./tests/fixtures:/tmp/fixtures"
    healthcheck:
      test: bash /scripts/wait/health_check.sh
      interval: 15s
      timeout: 10s
      retries: 3

  consumer-mock-notify:
    image: consumer-mock-notify:latest
    container_name: consumer-notify
    build:
      context: .
      dockerfile: docker/mock-notify/Dockerfile
    command:
      - "mock"
      - "-h"
      - "0.0.0.0"
      - "/app/mock-notify/openapi.yml"
    volumes:
      - "./docker/mock-notify:/app/mock-notify"
    ports:
      - "4010:4010"
    healthcheck:
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 10s

  consumer-mock-sirius:
    image: consumer-mock-sirius:latest
    container_name: consumer-sirius
    build:
      context: .
      dockerfile: docker/mock-sirius/Dockerfile
    command:
      - "mock"
      - "-p"
      - "4011"
      - "-h"
      - "0.0.0.0"
      - "/app/mock-sirius/openapi.yml"
    volumes:
      - "./docker/mock-sirius:/app/mock-sirius"
    ports:
      - "4011:4011"

  mock-notify-ci:
    image: mock-notify:latest
    container_name: consumer-mock-notify
    build:
      context: .
      dockerfile: docker/mock-notify/Dockerfile
    command:
      - "mock"
      - "-h"
      - "0.0.0.0"
      - "/app/mock-notify/openapi.yml"
    ports:
      - "4010:4010"
    healthcheck:
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 10s

  mock-sirius-ci:
    image: mock-sirius:latest
    container_name: consumer-mock-sirius
    build:
      context: .
      dockerfile: docker/mock-sirius/Dockerfile
    command:
      - "mock"
      - "-p"
      - "4011"
      - "-h"
      - "0.0.0.0"
      - "/app/mock-sirius/openapi.yml"
    ports:
      - "4011:4011"
    healthcheck:
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 10s

  composer:
    image: composer
    command: [ "install" ]
    volumes:
      - ~/.composer:/tmp
      - ./:/app
