---
version: "3.6"

services:

  consumer:
    image: notify-queue-consumer:latest
    build: .
    command: ["php", "-f", "public/consumer.php"]

  test:
    image: notify-queue-consumer:latest
    volumes:
      - .:/var/www
    command:
      - "./vendor/bin/phpunit"
      - "--configuration=phpunit.xml"
      - "--testsuite=unit"
      - "--log-junit=build/output/unit-tests.xml"

  phpstan:
    image: notify-queue-consumer:latest
    volumes:
      - ./vendor:/var/www/vendor
    command:
      - "ls"
      - "-la"
#      - "--level=7"
#      - "/var/www/src"

  lint:
    image: cytopia/phpcs:latest-php7.4
    volumes:
      - ./src:/data/src
      - ./public:/data/public
    command:
      - -p
      - --report=checkstyle
      - --standard=PSR12
      - --warning-severity=0
      - /data/src
      - /data/public
