version: 2.1

workflows:
  pr-build-and-test:
    jobs:
      - test_notify_queue_consumer:
          name: test_notify_queue_consumer
      - build_notify_queue_consumer:
          name: build_notify_queue_consumer
          requires: [test_notify_queue_consumer]

orbs:
  notify_queue_consumer:
    commands:
      install_aws_cli:
        steps:
          - run:
              name: Install AWS CLI
              command: sudo pip3 install awscli --upgrade
      ecr_login:
        steps:
          - run:
              name: Login to ECR
              command: |
                temp_role=$(aws sts assume-role --role-arn arn:aws:iam::311462405659:role/sirius-ci --role-session-name ci)
                export AWS_ACCESS_KEY_ID=$(echo $temp_role | jq .Credentials.AccessKeyId | xargs)
                export AWS_SECRET_ACCESS_KEY=$(echo $temp_role | jq .Credentials.SecretAccessKey | xargs)
                export AWS_SESSION_TOKEN=$(echo $temp_role | jq .Credentials.SessionToken | xargs)
                eval $(aws ecr get-login --no-include-email --region=eu-west-1)
    executors:
      python:
        docker: [image: circleci/python]

jobs:
  test_notify_queue_consumer:
    executor: notify_queue_consumer/python
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
          docker_layer_caching: false
      - run:
          name: Build container
          command: docker-compose build
      - run:
          name: Run Linting Checks
          command: docker-compose run --rm lint
      - run:
          name: Run Static Analysis
          command: docker-compose run --rm phpstan-ci
      - run:
          name: Run Unit Tests
          command: docker-compose run --rm test-ci
      - store_test_results:
          path: build/output

  build_notify_queue_consumer:
    executor: notify_queue_consumer/python
    parameters:
      container_repo_url:
        type: string
        default: 311462405659.dkr.ecr.eu-west-1.amazonaws.com/notify-queue-consumer
    steps:
      - checkout
      - notify_queue_consumer/install_aws_cli
      - setup_remote_docker:
          version: 18.06.0-ce
          docker_layer_caching: false
      - notify_queue_consumer/ecr_login
      - run:
          name: Build
          command: docker build --file Dockerfile --tag notify-queue-consumer:latest .
      - run:
          name: Push container
          command: |
            export SHORT_HASH=${CIRCLE_SHA1:0:7} >> $BASH_ENV
            docker tag notify-queue-consumer:latest << parameters.container_repo_url >>:latest
            docker tag notify-queue-consumer:latest << parameters.container_repo_url >>:$CIRCLE_BRANCH-$SHORT_HASH
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              # We want all of the tags pushed
              docker push << parameters.container_repo_url >>
            else
              docker push << parameters.container_repo_url >>:$CIRCLE_BRANCH-$SHORT_HASH
            fi
