openapi: 3.0.0
info:
  title: Notifications API
  description: Backwards engineered and limited to what we need to mock; deprecate if notifications provide an api spec
  version: 0.1.0
servers:
  - url: http://localhost:4010
    description: Local Prism server
#  - url: https://api.notifications.service.gov.uk
#    description: Main (production) server
paths:
  "/v2/notifications/{id}":
    get:
      summary: Check status
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
            example: 9a83b0bb-a534-41a5-849f-dbc39aee4d3d
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notification'
              examples:
                validation-failed:
                  summary: Validation failed
                  value:
                    status: validation-failed
                    id: 9a83b0bb-a534-41a5-849f-dbc39aee4d3d
                    reference: "1234"
                pending-virus-check:
                  summary: Pending virus check
                  value:
                    status: pending-virus-check
                    id: 9a83b0bb-a534-41a5-849f-dbc39aee4d3d
                    reference: "1234"

  "/v2/notifications/letter":
    post:
      summary: Send a precompiled letter
      responses:
        '201':
          description: Simple post example - note that request body isn't mocked
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  postage:
                    type: string
                    default: second
                  reference:
                    type: string
                    default: client-defined-reference
        '400':
          description: Error response example
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      $ref: '#/components/schemas/NotifyError'
                  status_code:
                    type: int
                    enum:
                      - 400
                      - 429

  "/v2/notifications?reference={reference}":
    get:
      summary: Get the status of multiple messages
      description: https://docs.notifications.service.gov.uk/php.html#get-the-status-of-multiple-messages
      parameters:
        - name: reference
          in: query
          required: true # not in the actual api
          schema:
            type: string
      # https://swagger.io/docs/specification/describing-responses/
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: object
                properties:
                  notifications:
                    type: array
                    items:
                      $ref: '#/components/schemas/Notification'
              examples:
                none:
                  summary: Return a notification
                  value:
                    notifications: []
                one:
                  summary: No matching notification found
                  value:
                    notifications:
                      - id: 9a83b0bb-a534-41a5-849f-dbc39aee4d3d

components:
  # https://swagger.io/docs/specification/components/
  schemas:
    Notification:
      type: object
      properties:
        id:
          type: string
          format: uuid
        reference:
          type: string
          default: client-defined-reference
        status:
          type: string
          enum:
            - pending-virus-check
            - accepted
            - delivered
            - received
            - failed
            - permanent-failure
            - temporary-failure
            - technical-failure
            - virus-scan-failed
            - validation-failed
          default: accepted
    NotifyError:
      type: object
      properties:
        error:
          type: string
          enum:
            - ValidationError
            - BadRequestError
            - RateLimitError
            - TooManyRequestsError
        message:
          type: string
          example: postage invalid. It must be either first or second.
