name: Generate Scan Report

on:
  schedule:
    # Every Friday at 16:30 UTC
    - cron: '30 16 * * 5'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: ministryofjustice/opg-repository-scanner@71b6f17bc23c826d4755624072bd289317368da7 # v2.0.18
